package br.com.aajj.ajj_backend.domain;

public enum Belt {
    BRANCA, CINZA_E_BRANCA, CINZA, CINZA_E_PRETA, AMARELA_E_BRANCA, AMARELA, AMARELA_E_PRETA, LARANJA_E_BRANCA,
    LARANJA, LARANJA_E_PRETA, VERDE_E_BRANCA, VERDE, VERDE_E_PRETA, AZUL, ROXA, MARROM, PRETA
}
